apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: qva6qn1uj-go 
  janus-idp.io/tekton: qva6qn1uj-go
  backstage.io/kubernetes-id: qva6qn1uj-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qva6qn1uj-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml