apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: qva6qn1uj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  qva6qn1uj-go
    app.kubernetes.io/part-of: qva6qn1uj-go-gitops  
  name: qva6qn1uj-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  qva6qn1uj-go 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  qva6qn1uj-go
    spec:
      containers:
      - image: quay.io/redhat-appstudio/rhtap-task-runner:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081 
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081 
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081 
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi    
        env:
        - name: GIT_REPO
          value: https://github.com/rhtap-rhdh-qe/qva6qn1uj-go-gitops
      imagePullSecrets:
        - name: tssc-image-registry-auth
