apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qva6qn1uj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qva6qn1uj-go 
  name: qva6qn1uj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qva6qn1uj-go 
